# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o
obj-$(CONFIG_EXYNOS_WD_DVFS)	+= exynos_ppmu.o
obj-$(CONFIG_ARM_EXYNOS7885_BUS_DEVFREQ)+= exynos7885_bus_mif.o exynos7885_bus_int.o exynos7885_bus_disp.o exynos7885_bus_cam.o exynos7885_bus_aud.o exynos7885_bus_fsys.o
