#
# Makefile for BTS.
#

obj-$(CONFIG_EXYNOS7885_BTS)    += cal_bts7885.o bts-exynos7885.o
obj-$(CONFIG_EXYNOS8890_BTS)    += cal_bts8890.o bts-exynos8890.o
obj-$(CONFIG_EXYNOS9610_BTS)    += cal_bts9610.o bts-exynos9610.o
